services:
  postgres:
    container_name: hyperpage-dev-postgres
    env_file:
      - .env.dev
    volumes:
      - postgres-dev_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d hyperpage-dev"]
      interval: 1m30s
      timeout: 30s
      retries: 5
      start_period: 30s

  redis:
    container_name: hyperpage-dev-redis
    env_file:
      - .env.dev
    volumes:
      - redis-dev_data:/data

  hyperpage:
    container_name: hyperpage-dev-app
    env_file:
      - .env.dev

volumes:
  postgres-dev_data:
    driver: local
  redis-dev_data:
    driver: local
